Repository OCA/purchase-reporting, pull requests merged in 2024-05, with the labels that each got.

#64 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .oca_hooks.cfg
  .pre-commit-config.yaml
Labels: help wanted, needs review, bot is merging ⏳

#63 [15.0][ADD] purchase_order_report_grouped_by_vendor: New module
  purchase_order_report_grouped_by_vendor/README.rst
  purchase_order_report_grouped_by_vendor/__init__.py
  purchase_order_report_grouped_by_vendor/__manifest__.py
  purchase_order_report_grouped_by_vendor/i18n/es.po
  purchase_order_report_grouped_by_vendor/i18n/purchase_order_report_grouped_by_vendor.pot
  purchase_order_report_grouped_by_vendor/models/__init__.py
  purchase_order_report_grouped_by_vendor/models/purchase_order.py
  purchase_order_report_grouped_by_vendor/readme/CONTRIBUTORS.rst
  purchase_order_report_grouped_by_vendor/readme/DESCRIPTION.rst
  purchase_order_report_grouped_by_vendor/readme/USAGE.rst
  purchase_order_report_grouped_by_vendor/static/description/icon.png
  purchase_order_report_grouped_by_vendor/static/description/index.html
  purchase_order_report_grouped_by_vendor/tests/__init__.py
  purchase_order_report_grouped_by_vendor/tests/test_purchase_order_report_grouped_by_vendor.py
  purchase_order_report_grouped_by_vendor/views/report_purchase_order.xml
  setup/purchase_order_report_grouped_by_vendor/odoo/addons/purchase_order_report_grouped_by_vendor
  setup/purchase_order_report_grouped_by_vendor/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#67 [ADD] [16.0] purchase_packaging_report
  purchase_packaging_report/README.rst
  purchase_packaging_report/__init__.py
  purchase_packaging_report/__manifest__.py
  purchase_packaging_report/i18n/es.po
  purchase_packaging_report/i18n/purchase_packaging_report.pot
  purchase_packaging_report/readme/CONFIGURE.md
  purchase_packaging_report/readme/CONTRIBUTORS.md
  purchase_packaging_report/readme/DESCRIPTION.md
  purchase_packaging_report/readme/USAGE.md
  purchase_packaging_report/report/__init__.py
  purchase_packaging_report/report/purchase_order_templates.xml
  purchase_packaging_report/report/purchase_quotation_templates.xml
  purchase_packaging_report/report/purchase_report.py
  purchase_packaging_report/report/purchase_report_views.xml
  purchase_packaging_report/static/description/icon.png
  purchase_packaging_report/static/description/index.html
  setup/purchase_packaging_report/odoo/addons/purchase_packaging_report
  setup/purchase_packaging_report/setup.py
Labels: approved, bot is merging ⏳
