Repository OCA/purchase-reporting, pull requests merged in 2024-04, with the labels that each got.

#62 [16.0][MIG] purchase_comment_template: Migration to 16.0
  purchase_comment_template/README.rst
  purchase_comment_template/__init__.py
  purchase_comment_template/__manifest__.py
  purchase_comment_template/i18n/de.po
  purchase_comment_template/i18n/es.po
  purchase_comment_template/i18n/fr.po
  purchase_comment_template/i18n/it.po
  purchase_comment_template/i18n/purchase_comment_template.pot
  purchase_comment_template/models/__init__.py
  purchase_comment_template/models/purchase_order.py
  purchase_comment_template/readme/CONTRIBUTORS.rst
  purchase_comment_template/readme/DESCRIPTION.rst
  purchase_comment_template/readme/INSTALL.rst
  purchase_comment_template/security/ir.model.access.csv
  purchase_comment_template/static/description/icon.png
  purchase_comment_template/static/description/index.html
  purchase_comment_template/tests/__init__.py
  purchase_comment_template/tests/test_purchase_order_report.py
  purchase_comment_template/views/base_comment_template_view.xml
  purchase_comment_template/views/purchase_order_view.xml
  purchase_comment_template/views/report_purchaseorder.xml
  purchase_comment_template/views/report_quotation.xml
  setup/purchase_comment_template/odoo/addons/purchase_comment_template
  setup/purchase_comment_template/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#48 [16.0] [MIG] purchase_backorder
  purchase_backorder/README.rst
  purchase_backorder/__init__.py
  purchase_backorder/__manifest__.py
  purchase_backorder/i18n/de.po
  purchase_backorder/i18n/purchase_backorder.pot
  purchase_backorder/i18n/sl.po
  purchase_backorder/models/__init__.py
  purchase_backorder/models/purchase_order.py
  purchase_backorder/models/purchase_order_line.py
  purchase_backorder/readme/CONTRIBUTORS.rst
  purchase_backorder/readme/DESCRIPTION.rst
  purchase_backorder/readme/USAGE.rst
  purchase_backorder/report/po_backorder_report.xml
  purchase_backorder/security/ir.model.access.csv
  purchase_backorder/static/description/icon.png
  purchase_backorder/static/description/index.html
  purchase_backorder/views/po_backorder_view.xml
  purchase_backorder/views/purchase_view.xml
  purchase_backorder/wizard/__init__.py
  purchase_backorder/wizard/po_backorder_wizard.py
  purchase_backorder/wizard/po_backorder_wizard_view.xml
  setup/purchase_backorder/odoo/addons/purchase_backorder
  setup/purchase_backorder/setup.py
Labels: approved, bot is merging ⏳

#55 Add Copier
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
Labels: bot is merging ⏳
